version: "3.1"
services:  
    monetdb:
        image: monetdb/monetdb
        restart: always
        volumes: 
            - ./scripts/dados_sciphy.sql:/home/monetdb/dados_sciphy.sql
        ports:
            - "50000:50000"
